services:
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - "DB_URL=jdbc:postgresql://postgres:5432/mydatabase"
      - "DB_NAME=postgres"
      - "DB_PASSWORD=password"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=create"
  postgres:
    image: postgres:alpine
    container_name: bookclub_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase