services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    container_name: bookclub_backend
    environment:
      - SERVER_PORT=8080
      - SERVER_CONTEXT_PATH=/api/v1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_HIBERNATE_DIALECT=PostgreSQLDialect
      - CORS_ALLOWED_ORIGIN=http://localhost:2000,http://localhost:3000
      - CORS_ALLOWED_HEADERS=*
      - CORS_ALLOWED_METHODS=GET,POST,DELETE,PUT
      - CORS_SET_MAXAGE=3000
      - SPRING_OAUTH2_JWT_ISSUER_URI=https://accounts.google.com
      - SPRING_OAUTH2_JWT_AUTH_URI=https://www.googleapis.com/oauth2/v3/certs
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: bookclub_db
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password