services:
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://bookclub_db/postgres"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=tjvbookclub"
  postgres:
    image: postgres:alpine
    container_name: bookclub_db
    environment:
      - "POSTGRES_PASSWORD=tjvbookclub"