services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    container_name: bookclub_backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - CORS_ALLOWED_ORIGIN=http://localhost:2000,http://localhost:3000
      - CORS_ALLOWED_HEADERS=*
      - CORS_ALLOWED_METHODS=*
  db:
    image: postgres:alpine
    container_name: bookclub_db
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password